name: app
description: The PRF Super App
version: 2.17.07+21707
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  auto_route: ^8.1.4
  awesome_notifications: ^0.10.0
  awesome_notifications_core: ^0.10.0
  bloc: ^9.0.0
  build_version: ^2.1.1
  collection: ^1.19.0
  dart_pusher_channels: ^1.2.3
  dio: ^5.7.0
  extended_image: ^9.0.9
  firebase_analytics: ^11.4.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_ui: ^0.8.0+1
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_widget_from_html: ^0.15.3
  freezed_annotation: ^2.4.4
  full_screen_image: ^2.0.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  google_sign_in_ios: ^5.7.8
  google_sign_in_web: ^0.12.4+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  map_launcher: ^3.5.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  slugify: ^2.0.0
  upgrader: ^11.3.1
  url_launcher: ^6.3.1
  wechat_assets_picker: ^9.4.2
  wolt_modal_sheet: ^0.10.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/authentication/
