org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC
kotlin.daemon.jvmargs=-Xmx1024m
org.gradle.workers.max=2
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=false

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=true
