// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTYauZ_0oaxcd-CS5tEmQVxfWFahIlR4',
    appId: '1:373327072646:android:d9bc80cec10952325c3007',
    messagingSenderId: '373327072646',
    projectId: 'hosanna-mt',
    storageBucket: 'hosanna-mt.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQcmn2k0_LpSAxpkNAfKoX_8vqzBg2DM8',
    appId: '1:373327072646:ios:66467d115d1a2fc95c3007',
    messagingSenderId: '373327072646',
    projectId: 'hosanna-mt',
    storageBucket: 'hosanna-mt.firebasestorage.app',
    androidClientId:
        '373327072646-gfihsd0rogf1a0avc4vk94p7del0p0ng.apps.googleusercontent.com',
    iosBundleId: 'hmt.parkroadfellowship.org',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbI5VykxCvu6iStjKav08Wlk8zpSnIHiI',
    appId: '1:373327072646:web:79248e00603814105c3007',
    messagingSenderId: '373327072646',
    projectId: 'hosanna-mt',
    authDomain: 'hosanna-mt.firebaseapp.com',
    storageBucket: 'hosanna-mt.firebasestorage.app',
    measurementId: 'G-XLM8D3JQBL',
  );
}
