// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRptZXBum6K_NdaTF5alei7Z9H55kIfg',
    appId: '1:899177334428:android:0c399ecc63460bc4b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4GCdn77Z79Z7lxkNbaUImu7iVYGDBSw4',
    appId: '1:899177334428:ios:1447634a6c2d9dd0b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    iosClientId: '899177334428-4d9ar4pslt6tnfg8n9j0sbe41a0o068g'
        '.apps.googleusercontent.com',
    iosBundleId: 'org.parkroadfellowship.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjit7qKk0sqo0cxNrhreR0gNfSTlSc00',
    appId: '1:899177334428:web:f93f20d18f092d8cb18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    authDomain: 'parkroad-fellowship.firebaseapp.com',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    measurementId: 'G-8PMMBCWG0R',
  );
}
