import 'dart:async';

import 'package:hive_ce_flutter/hive_flutter.dart';

/// Abstract base for all Hive-backed entity CRUD services.
///
/// Stores entities as JSON maps ([Map<String, dynamic>]) so that no additional
/// Hive type adapters are required – every remote model already has
/// `toJson()` / `fromJson()` generated by freezed/json_serializable.
abstract class BaseHiveDbService<TRemote> {
  /// The name of the Hive box that backs this service.
  String get boxName;

  /// Returns the unique string key for an entity (typically its ULID).
  String getKey(TRemote entity);

  /// Serialises [entity] to a JSON map for storage.
  Map<String, dynamic> toJson(TRemote entity);

  /// Deserialises a JSON map retrieved from the box back to [TRemote].
  TRemote fromJson(Map<String, dynamic> json);

  Box<dynamic> get _box => Hive.box<dynamic>(boxName);

  // ----- Identity helpers kept for ResourceCubit compatibility -----

  TRemote localToRemote(TRemote local) => local;
  List<TRemote> localToRemoteList(List<TRemote> locals) => locals;

  // ----- CRUD -----

  Future<List<TRemote>> list() async {
    return _box.values
        .map((v) => fromJson(Map<String, dynamic>.from(v as Map)))
        .toList();
  }

  Future<TRemote?> get(String key) async {
    final v = _box.get(key);
    if (v == null) return null;
    return fromJson(Map<String, dynamic>.from(v as Map));
  }

  Future<void> persistEntity(TRemote entity) async {
    final key = getKey(entity);
    final newJson = toJson(entity);
    final existing = _box.get(key);

    if (existing != null) {
      final existingJson = Map<String, dynamic>.from(existing as Map);
      // Strip nulls from incoming JSON so explicit null relations (due to missing includes)
      // do not overwrite and destroy locally cached relationships.
      final nonNullNewJson = Map<String, dynamic>.from(newJson)
        ..removeWhere((k, v) => v == null);
      await _box.put(key, {...existingJson, ...nonNullNewJson});
    } else {
      await _box.put(key, newJson);
    }
  }

  Future<void> persistEntities(List<TRemote> entities) async {
    final map = <String, dynamic>{};
    for (final e in entities) {
      final key = getKey(e);
      final newJson = toJson(e);
      final existing = _box.get(key);

      if (existing != null) {
        final existingJson = Map<String, dynamic>.from(existing as Map);
        // Strip nulls to prevent destroying un-hydrated local relationships
        final nonNullNewJson = Map<String, dynamic>.from(newJson)
          ..removeWhere((k, v) => v == null);
        map[key] = {...existingJson, ...nonNullNewJson};
      } else {
        map[key] = newJson;
      }
    }
    await _box.putAll(map);
  }

  Future<void> deleteByKey(String key) async {
    await _box.delete(key);
  }

  Future<bool> exists(String key) async => _box.containsKey(key);

  Future<void> clearAll() async => _box.clear();

  Future<int> count() async => _box.length;

  /// Returns all entities matching [predicate].
  Future<List<TRemote>> filterBy(bool Function(TRemote) predicate) async {
    final all = await list();
    return all.where(predicate).toList();
  }

  // ----- List stream -----

  /// A reactive stream broadcasting the full list whenever the Hive box updates.
  Stream<List<TRemote>> get stream async* {
    yield await list();
    await for (final _ in _box.watch()) {
      yield await list();
    }
  }

  // ----- Single-item stream -----

  /// A reactive stream broadcasting a single item whenever its key updates in the Hive box.
  Stream<TRemote?> watchItem(String key) async* {
    yield await get(key);
    await for (final _ in _box.watch(key: key)) {
      yield await get(key);
    }
  }
}
