import 'dart:async';

import 'package:hive_ce_flutter/hive_flutter.dart';

/// Abstract base for all Hive-backed entity CRUD services.
///
/// Stores entities as JSON maps ([Map<String, dynamic>]) so that no additional
/// Hive type adapters are required – every remote model already has
/// `toJson()` / `fromJson()` generated by freezed/json_serializable.
abstract class BaseHiveDbService<TRemote> {
  /// The name of the Hive box that backs this service.
  String get boxName;

  /// Returns the unique string key for an entity (typically its ULID).
  String getKey(TRemote entity);

  /// Serialises [entity] to a JSON map for storage.
  Map<String, dynamic> toJson(TRemote entity);

  /// Deserialises a JSON map retrieved from the box back to [TRemote].
  TRemote fromJson(Map<String, dynamic> json);

  Box<dynamic> get _box => Hive.box<dynamic>(boxName);

  // ----- Identity helpers kept for ResourceCubit compatibility -----

  TRemote localToRemote(TRemote local) => local;
  List<TRemote> localToRemoteList(List<TRemote> locals) => locals;

  // ----- CRUD -----

  Future<List<TRemote>> list() async {
    return _box.values
        .map((v) => fromJson(Map<String, dynamic>.from(v as Map)))
        .toList();
  }

  Future<TRemote?> get(String key) async {
    final v = _box.get(key);
    if (v == null) return null;
    return fromJson(Map<String, dynamic>.from(v as Map));
  }

  Future<void> persistEntity(TRemote entity) async {
    await _box.put(getKey(entity), toJson(entity));
  }

  Future<void> persistEntities(List<TRemote> entities) async {
    final map = {for (final e in entities) getKey(e): toJson(e)};
    await _box.putAll(map);
  }

  Future<void> deleteByKey(String key) async {
    await _box.delete(key);
  }

  Future<bool> exists(String key) async => _box.containsKey(key);

  Future<void> clearAll() async => _box.clear();

  Future<int> count() async => _box.length;

  /// Returns all entities matching [predicate].
  Future<List<TRemote>> filterBy(bool Function(TRemote) predicate) async {
    final all = await list();
    return all.where(predicate).toList();
  }

  // ----- List stream -----

  StreamController<List<TRemote>>? _streamController;

  Stream<List<TRemote>> get stream {
    _streamController ??= StreamController<List<TRemote>>.broadcast();
    return _streamController!.stream;
  }

  Future<void> refreshStream() async {
    _streamController ??= StreamController<List<TRemote>>.broadcast();
    _streamController!.add(await list());
  }

  Future<void> closeStream() async {
    await _streamController?.close();
    _streamController = null;
  }

  // ----- Single-item stream -----

  StreamController<TRemote?>? _itemStreamController;

  Stream<TRemote?> get itemStream {
    _itemStreamController ??= StreamController<TRemote?>.broadcast();
    return _itemStreamController!.stream;
  }

  Future<void> refreshItemStream(String key) async {
    _itemStreamController ??= StreamController<TRemote?>.broadcast();
    _itemStreamController!.add(await get(key));
  }

  Future<void> closeItemStream() async {
    await _itemStreamController?.close();
    _itemStreamController = null;
  }
}
