import 'dart:async';

import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:logger/logger.dart';

/// Abstract base for all Hive-backed entity CRUD services.
///
/// Stores entities as JSON maps ([Map<String, dynamic>]) so that no additional
/// Hive type adapters are required – every remote model already has
/// `toJson()` / `fromJson()` generated by freezed/json_serializable.
abstract class BaseHiveDbService<TRemote> {
  /// The name of the Hive box that backs this service.
  String get boxName;

  /// Returns the unique string key for an entity (typically its ULID).
  String getKey(TRemote entity);

  /// Serialises [entity] to a JSON map for storage.
  Map<String, dynamic> toJson(TRemote entity);

  /// Deserialises a JSON map retrieved from the box back to [TRemote].
  TRemote fromJson(Map<String, dynamic> json);

  Box<dynamic> get _box => Hive.box<dynamic>(boxName);
  final _logger = Logger();

  // ----- Identity helpers kept for ResourceCubit compatibility -----

  TRemote localToRemote(TRemote local) => local;
  List<TRemote> localToRemoteList(List<TRemote> locals) => locals;

  // ----- CRUD -----

  Future<List<TRemote>> list() async {
    final items = <TRemote>[];

    for (final entry in _box.toMap().entries) {
      try {
        final json = _toStringKeyedMap(entry.value);
        items.add(fromJson(json));
      } catch (e, s) {
        _logger.e(
          'HiveDB[$boxName]: failed to deserialize key ${entry.key}',
          error: e,
          stackTrace: s,
        );
      }
    }

    return items;
  }

  Future<TRemote?> get(String key) async {
    final value = _box.get(key);
    if (value == null) return null;
    try {
      return fromJson(_toStringKeyedMap(value));
    } catch (e, s) {
      _logger.e(
        'HiveDB[$boxName]: failed to deserialize key $key',
        error: e,
        stackTrace: s,
      );
      return null;
    }
  }

  Future<void> persistEntity(TRemote entity) async {
    final key = getKey(entity);
    final newJson = _toStringKeyedMap(toJson(entity));
    final existing = _box.get(key);

    if (existing != null) {
      final existingJson = _toStringKeyedMap(existing);
      final nonNullNewJson = Map<String, dynamic>.from(newJson)
        ..removeWhere((k, v) => v == null);
      await _box.put(key, {...existingJson, ...nonNullNewJson});
    } else {
      await _box.put(key, newJson);
    }
  }

  Future<void> persistEntities(List<TRemote> entities) async {
    final map = <String, dynamic>{};

    for (final e in entities) {
      final key = getKey(e);
      final newJson = _toStringKeyedMap(toJson(e));
      final existing = _box.get(key);

      if (existing != null) {
        final existingJson = _toStringKeyedMap(existing);
        final nonNullNewJson = Map<String, dynamic>.from(newJson)
          ..removeWhere((k, v) => v == null);
        map[key] = {...existingJson, ...nonNullNewJson};
      } else {
        map[key] = newJson;
      }
    }

    await _box.putAll(map);
  }

  Map<String, dynamic> _toStringKeyedMap(dynamic value) {
    if (value is! Map) {
      throw StateError(
        'HiveDB[$boxName]: expected Map but got ${value.runtimeType}',
      );
    }

    final normalized = _normalizeJsonValue(value);
    if (normalized is! Map) {
      throw StateError(
        'HiveDB[$boxName]: normalized value is not a Map (${normalized.runtimeType})',
      );
    }

    return Map<String, dynamic>.from(normalized);
  }

  dynamic _normalizeJsonValue(dynamic value) {
    if (value is Map) {
      return value.map<String, dynamic>(
        (key, mapValue) => MapEntry(
          key.toString(),
          _normalizeJsonValue(mapValue),
        ),
      );
    }

    if (value is List) {
      return value.map(_normalizeJsonValue).toList();
    }

    return value;
  }

  Future<void> deleteByKey(String key) async {
    await _box.delete(key);
  }

  Future<bool> exists(String key) async => _box.containsKey(key);

  Future<void> clearAll() async => _box.clear();

  Future<int> count() async => _box.length;

  /// Returns all entities matching [predicate].
  Future<List<TRemote>> filterBy(List<bool> Function(TRemote) predicate) async {
    final all = await list();
    return all.where((e) => predicate(e).every((b) => b)).toList();
  }

  // ----- List stream -----

  /// A reactive stream broadcasting the full list whenever the Hive box updates.
  Stream<List<TRemote>> get stream async* {
    yield await list();
    await for (final _ in _box.watch()) {
      yield await list();
    }
  }

  // ----- Single-item stream -----

  /// A reactive stream broadcasting a single item whenever its key updates in the Hive box.
  Stream<TRemote?> watchItem(String key) async* {
    yield await get(key);
    await for (final _ in _box.watch(key: key)) {
      yield await get(key);
    }
  }
}
