name: Deploy Staging

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes for this staging build"
        required: false
        default: "Staging build"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-apk:
    name: Build & Distribute APK (Staging)
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Flutter Setup
        uses: ./.github/actions/flutter-setup
        with:
          skip-analysis: "true"

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v2.0
        with:
          fileName: key.jks
          encodedString: ${{ secrets.RELEASE_KEYSTORE }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" >> android/key.properties
          echo "keyPassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.RELEASE_KEYSTORE_ALIAS }}" >> android/key.properties

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/emulator
          sudo rm -rf /usr/local/lib/android/sdk/system-images
          df -h
          
      - name: Build APK
        run: |
          flutter build apk \
            --flavor staging \
            --target lib/main_staging.dart \
            --release

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_STG_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: dev-team
          releaseNotes: ${{ github.event.inputs.notes }}
          file: build/app/outputs/flutter-apk/app-staging-release.apk
