name: Deploy Development

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes for this development build"
        required: false
        default: "Development build"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build APK (Dev)
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Flutter Setup
        uses: ./.github/actions/flutter-setup
        with:
          skip-analysis: "true"

      - name: Android Setup
        uses: ./.github/actions/android-setup
        with:
          keystore: ${{ secrets.RELEASE_KEYSTORE }}
          keystore-passphrase: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          keystore-password: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}

      - name: Build APK
        run: |
          flutter build apk \
            --flavor development \
            --target lib/main_development.dart \
            --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v7
        with:
          name: apk-artifact
          path: build/app/outputs/flutter-apk/app-development-release.apk
          retention-days: 1

  firebase:
    name: Push to Firebase (Dev)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v8
        with:
          name: apk-artifact

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_DEV_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: dev-team
          releaseNotes: ${{ github.event.inputs.notes }}
          file: app-development-release.apk
