name: Generate Prod APK

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: 🗄️ Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 🗄️ Cache Pub (Dart/Flutter)
        uses: actions/cache@v5
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "adopt"
          cache: gradle

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3"

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: 🧹 Clean build cache
        run: |
          flutter clean
          rm -rf build
          rm -rf .dart_tool

      - name: 📦 Install Dependencies
        run: flutter packages get

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: ⚙️ Code Generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 🕵️ Analyse
        run: flutter analyze lib

      - name: ⚙️ Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: key.jks
          encodedString: ${{ secrets.RELEASE_KEYSTORE }}

      - name: 🔐 Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" >> android/key.properties
          echo "keyPassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.RELEASE_KEYSTORE_ALIAS }}" >> android/key.properties

      - name: ⚙️ Build APK
        run: flutter build apk --flavor development --target lib/main_development.dart --release

      - name: ☁ Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_DEV_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: dev-team
          file: build/app/outputs/flutter-apk/app-development-release.apk
